[package]
name = "i3enhancer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked_hash_set = "0.1.4"

[dependencies.i3ipc]
version= "0.10.1"
